### ISSUE TITLE
*discounting

### ISSUE THREAD

**Issue by RobertASmith** [bitowaqr/emsr_course#4]
https://github.com/bitowaqr/emsr_course/blob/488142aed5db1d1df2970fabfa3df0f0619c0ac7/PSM/exercises/psm_exercise_2.R#L4

**Comment by RobertASmith** [comment]
Also worth noting that we are not doing a half-cycle correction anywhere.

**Comment by RobertASmith** [comment]
which is fine, but you may get asked.

**Comment by bitowaqr** [comment]
spelling error corrected
yes, but no problem, because we can use hours as intervals

**Comment by RobertASmith** [comment]
OK great - that is a good response
